console.log("ktdol");
console.log("oqllr");
console.log("atcep");
console.log("xqbhh");
console.log("hgxps");
console.log("__");
console.log("tpicd")
console.log("cdusf")
console.log("wnggy")
console.log("paxmd")
console.log("xjmwo")
console.log("xiopm")
console.log("djbhb")
console.log("elsac")
console.log("ylqsx")
